version: "3.8"
services:
  node-util:
    build: ./
    stdin_open: true
    tty: true
    container_name: auth
    volumes:
      - ./:/usr/app
    env_file:
      - .env
    ports:
      - 3000:3000