apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: btd
spec:
  selector:
    app: auth
    tier: backend
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000 